branch-defaults:
  master:
    environment: myStartupApp-env
global:
  application_name: my-startup-app
  default_ec2_keyname: Ireland
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: eu-west-1
  profile: null
  sc: git
